/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vpn_VpnNativeBridge */

#ifndef _Included_vpn_VpnNativeBridge
#define _Included_vpn_VpnNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vpn_VpnNativeBridge
 * Method:    openDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vpn_VpnNativeBridge_openDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vpn_VpnNativeBridge
 * Method:    readPacket
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_vpn_VpnNativeBridge_readPacket
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     vpn_VpnNativeBridge
 * Method:    writePacket
 * Signature: (JLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_vpn_VpnNativeBridge_writePacket
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     vpn_VpnNativeBridge
 * Method:    closeDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vpn_VpnNativeBridge_closeDevice
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
